### ISSUE TITLE
Rendering code blocks incorrectly while included by warning info

### ISSUE THREAD

**Issue by Cloudac7** [chenggroup/chenggroup.github.io#29]
When I tried to use \`xxx\` in a warning alert, the page rendered it as a LaTex formula, which could not read. But if I use `\` to transfer, it would be fully rendered, regardless of the symbols.

**Comment by xjf729** [comment]
When you use 'include alert.html ...', please use plain text in `content` key, do not use markdown. If you surely want to enable code or emphasize or another markdown features, you may use html language.
